language: python
python:
  - "3.6"
cache: pip
install:
  - pip install pytest
  - pip install pytest-cov
script:
  - pytest --cov=xpath_validator --doctest-modules xpath_validator
after_success:
  - pip install coveralls
  - coveralls